components/actions/TaskList.js, styles/app/_app-styles.scss
- Move ToDos first
- Fix long url-links wrapping in text-content
- Fix lint warnings on TaskList component
=> Reorder task list

components/indicators/Connector.js, components/indicators/IndicatorCausal.js
Make causal chain visualization less buggy
=> Improve causal chain visualization

common/links.js, components/actions/ActionListFilters.js
Fix globalnav active section
Fix deleting action list active filters
=> Quickfix bugs

common/ThemedGlobalStyles.js, common/utils.js, components/Footer.js, components/actions/ActionHero.js, components/actions/ActionListFilters.js, components/actions/ResponsibleList.js, components/common/BadgeTooltip.js, components/common/SiteFooter.js, components/dashboard/BarSegment.js, components/home/HeroFullImage.js, components/indicators/IndicatorsHero.js, components/layout.js, pages/index.js, public/static/styles/liiku/custom.css, styles/lahti-ilmasto/_theme-variables.scss
Theme related quickfixes for new release
=> Theme update

components/common/Card.js, components/common/GlobalNav.js, components/common/StreamField.js, components/contentblocks/ActionListBlock.js, components/contentblocks/CategoryListBlock.js, components/contentblocks/CategoryPageHeaderBlock.js, components/contentblocks/QuestionAnswerBlock.js, pages/[...slug].js
Hope this is a good starting point.
=> Add ActionListBlock draft and get categories from API

README.md
Updated node and yarn versions
=> Updated node and yarn versions in README

components/common/Modal.tsx, components/graphs/StatusDonut.js
* added common modal component;
* on click on pie chart open modal with enlarged content.
=> Added a modal to pie charts

common/__tests__/utils.test.ts, common/hooks/localize-link.ts, common/utils.ts, components/plans/PlanChip.tsx, components/plans/PlanLink.tsx, components/plans/PlanSelector.tsx
Ensures that plan links include the current locale in the path. Cross plan action links are more finicky and may need to be handled in the backend, let’s discuss those separately.
---
- https://app.asana.com/0/0/1205193561208169
=> Persist language when changing plans

common/__generated__/graphql.ts, components/dashboard/ActionTableTooltips.tsx, components/dashboard/dashboard.constants.tsx, components/dashboard/dashboard.types.ts, components/orgs/OrgContent.tsx
Fixes some of the comments in https://github.com/kausaltech/kausal-watch-ui/pull/184. I've left some which relate to old code and the refactoring of interfaces to use types.
=> Address PR comments 

components/graphs/GraphAsTable.js, components/graphs/IndicatorGraph.tsx
Use custom color for goal lines from theme (theme side already deployed)
Remove area fill from goal lines after all
Some auto eslint changes & small style tweaks
=> Use custom goal line color from theme

components/actions/CategoryActionList.js, locales/da/common.json, locales/de-CH/common.json, locales/de/common.json, locales/en/common.json, locales/es/common.json, locales/fi/common.json, locales/sv/common.json
ChatGPT translations to be verified internally
=> Improve action list copy for initial tree map state

.eslintrc.json, common/__generated__/graphql.ts, components/common/StreamField.tsx, components/contentblocks/IndicatorGroupBlock.tsx, components/indicators/IndicatorHighlightCard.tsx
Depends on [backend changes](https://github.com/kausaltech/kausal-watch-private/pull/76).
=> Support custom indicator group titles and all indicators link

components/common/SiteFooter.tsx
=> Type site footer

components/dashboard/cells/StatusCell.tsx
---
- https://app.asana.com/0/0/1205844800130211
=> Hide unknown status from the actions table

components/actions/ActionContent.tsx, components/actions/blocks/ActionRelatedIndicatorsBlock.tsx, components/indicators/IndicatorCausalVisualisation.tsx
---
- https://app.asana.com/0/0/1205878446562184
=> Filter assumed draft related indicators

components/contentblocks/CategoryPageHeaderBlock.tsx, pages/[...slug].tsx
---
- https://app.asana.com/0/0/1205842398616946
=> Default category page bg color to white

components/home/HeroFullImage.tsx
---
- https://app.asana.com/0/0/1206010535152027
- https://app.asana.com/0/0/1205842398616949
=> Make heroBlock h1 color headingColor by default

components/actions/CategoryTags.tsx, components/common/Accordion.tsx, components/common/Modal.tsx, components/common/PopoverTip.tsx, components/dashboard/dashboard.constants.tsx, components/graphs/StatusDonut.js, components/orgs/OrgSelector.js, locales/en/actions.json
Fixed WAVE accessibility errors for Durham
=> Fixed accessibility errors

components/contentblocks/RelatedPlanListBlock.tsx
Related Asana task https://app.asana.com/0/1202880927552397/1206091007672253/f
=> Set corresponding long name for a sibling plan

components/indicators/IndicatorProgressBar.js
before:
after:
before:
after:
before:
after:
=> Fix values rounding in indicator showcase

components/actions/ActionCardList.js, components/contentblocks/ActionListBlock.tsx
* Updated ActionCardList to conditionally render the "Other" category;
* Hid the "Other" title in ActionListBlock
Related asana task: https://app.asana.com/0/1202880927552397/1206148323634412/f
=> Hide Other category title on category page

components/common/ActionAttribute.tsx
Requested by Bremen whose primary brand colour is red and implies negative progress
=> Add themeable action attribute color

components/dashboard/cells/TasksStatusCell.tsx
Requires https://github.com/kausaltech/kausal-themes/pull/19
=> Support themeable task status colours

components/common/SearchView.js, components/common/Switch.js, components/indicators/IndicatorNormalizationSelect.tsx, components/indicators/IndicatorProgressBar.js, components/insight/InsightFilter.js
fixed critical accessibility html errors.
Related Asana task https://app.asana.com/0/1202880927552397/1206128477196469/f
=> Fixed critical accessibility errors

components/common/AnnouncementBanner.tsx, components/common/ApplicationStateBanner.js, components/versioning/PlanVersionBanner.tsx, context/queries/plan.js
=> Add AnnouncementBanner component to display sitewide announcements

components/graphs/IndicatorGraph.tsx
---
- https://app.asana.com/0/0/1204520471559003
=> Enable downloading for indicator graph images

components/common/ApplicationStateBanner.js
`plan.generalContent.sitewideAnnouncement === ""` when no content is provided
=> Hide announcement banner element when no content is provided

components/indicators/IndicatorCard.tsx, components/indicators/IndicatorCausalVisualisation.tsx
Before
After
---
- https://app.asana.com/0/0/1206372264975886
=> Fix causal chain visualisation card sizing

.github/workflows/ci-e2e.yaml, README.md, components/common/NavbarSearch.js, e2e-tests/basic.spec.ts, e2e-tests/context.ts, package.json, playwright.config.ts, yarn.lock
Refactored test code, set 2 min timeout for each test, added env variable for page baseUrl, updated README.
=> Refactor playwright tests

app/[domain]/[lang]/[plan]/layout.tsx, sentry.client.config.ts, sentry.edge.config.ts, sentry.server.config.ts
Add additional context to support debugging the below error and add environment to Sentry errors.
https://sentry.kausal.tech/organizations/kausal/issues/4391/events/82c9ed4d58d6422695d61f59e52a2947/
=> Improve url error logging

components/actions/ActionListFilters.tsx
Magdalena noticed a string is not displayed properly: https://kausaltech.slack.com/archives/C038B91QJ10/p1706785499858319?thread_ts=1706623936.596349&cid=C038B91QJ10
=> Fix missing action term context for i18n string see-all-actions

app/[domain]/[lang]/[plan]/(with-layout-elements)/actions/[id]/page.tsx
---
- https://app.asana.com/0/0/1206492816208045
=> Added site name to openGraph for action page

.github/workflows/ci-e2e.yaml, e2e-tests/context.ts
PR for e2e tests CI workflow optimization
=> Fix/e2e GitHub workflow

common/search.ts, components/common/NavbarSearch.js
When typing the same search query twice, no results were displayed for the second query.
---
- https://app.asana.com/0/0/1206486884287691
=> Fix missing search results

components/HeaderComponent.js, components/common/TopToolBar.tsx, locales/en/common.json
Added a placeholder component for authenticated users. Right now there is no conditional rendering, waiting for the PR https://github.com/kausaltech/kausal-watch-ui/pull/281 to be merged.
=> Added TopToolBar component

utils/apollo.utils.ts
Log errors to the console locally in addition to Sentry if configured. Also log GQL network errors.
=> Improve local query error logging

components/actions/blocks/RestrictedBlockWrapper.tsx
This is a minor change discussed a few weeks back that I just remembered. Also works well on a coloured background.
=> Make restricted fields more subtle

components/dashboard/ActionList.tsx
[Sibling theme PR](https://github.com/kausaltech/kausal-themes/pull/24)
---
- https://app.asana.com/0/0/1206805407729685
=> Support hiding action dashboard pie charts

app/[domain]/[lang]/layout.tsx, components/actions/ActionContent.tsx
Should fix this recurring error from older browsers [in Sentry](https://sentry.kausal.tech/organizations/kausal/issues/5327/events/2ecbcfa90e43494287293947f4931483/) `globalThis is not defined`.
https://github.com/vercel/next.js/discussions/58818
Draft for now because it hasn't been thoroughly tested.
=> Add polyfill for globalThis

components/Footer.tsx, components/common/SiteFooter.tsx, queries/get-plan.ts
Show cross plan links in footer. Backend PR https://github.com/kausaltech/kausal-watch-private/pull/155/files
=> cross plan links to footer

components/indicators/IndicatorVisualisation.js, locales/da/common.json, locales/de/common.json, locales/en/common.json, locales/es/common.json, locales/fi/common.json, locales/pt-BR/common.json, locales/sv/common.json
Show reference under indicator graph.
Depends on this: https://github.com/kausaltech/kausal-watch-private/pull/158
Related asana: https://app.asana.com/0/1206017643443542/1206649411944555
=> Reference field for indicator

components/actions/ActionListFilters.tsx, fragments/action-list.fragment.ts, locales/da/actions.json, locales/de/actions.json, locales/en/actions.json, locales/es/actions.json, locales/fi/actions.json, locales/lv/actions.json, locales/pt-BR/actions.json, locales/sv/actions.json
=> Add continuous action filter block on action list page

components/actions/ActionCardList.js, components/dashboard/ActionList.tsx
Related Asana: https://app.asana.com/0/1205307984231852/1207019354167348/f
=> Group subplan actions by plan if no common category exists

components/common/GlobalNav.tsx, components/common/SiteFooter.tsx, package.json, yarn.lock
To accommodate request in https://app.asana.com/0/1205307984231852/1207019354167342/f
=> Use navLogoLink from themes

components/actions/ActionContent.tsx, components/actions/blocks/ActionDescriptionBlock.tsx, queries/get-action.ts
Take the field label from the block configuration of
the action page.
=> Display action description block field label if one is defined

components/Footer.tsx
Ludwigsburg requests to remove the feedback link from the Footer. 
Added conditional logic to control visibility of the link.
Related task in Asana https://app.asana.com/0/1206017643443542/1207019355477556/f
Corresponding PR https://github.com/kausaltech/kausal-themes/pull/29
=> Add conditional visibility of feedback link in Footer

common/search.ts
Use viewUrl in navbar search
Related asana: https://app.asana.com/0/1206017643443542/1206533591307373
=> Use viewUrl in navbar search

middleware.ts
---
- https://app.asana.com/0/0/1207146661131041
=> Support invalidating Apollo middleware cache

styles/GlobalStyles.tsx
Spotted by Samuel [here](https://climatedashboard.durham.ca/actions/A2)
| -- | -- |
| ![durham-ca-cap localhost_3000_actions_A2(iPhone SE) (3)](https://github.com/kausaltech/kausal-watch-ui/assets/15343658/8f90f753-0078-417e-b743-0906cc839976) | ![durham-ca-cap localhost_3000_actions_A2(iPhone SE) (1)](https://github.com/kausaltech/kausal-watch-ui/assets/15343658/b13248a7-bacf-4acc-9dd3-32375bd35715) |
=> Add max width to avoid image overflow on mobile

components/graphs/IndicatorGraph.tsx
@tituomin can you check, is there any other intentions in the original code that this might break?
https://app.asana.com/0/1203773030383189/1207097705965775/f
=> Make single time point bar charts multicolor

components/indicators/IndicatorCausalVisualisation.tsx
In indicators causal chain viz, show all strategic indicators instead of only the first one.
https://app.asana.com/0/1204822770753391/1207026021156163/f
=> Show multiple strategic indicators

common/ActionStatusSummary.ts, common/__generated__/graphql.ts, common/preprocess.ts, components/actions/ActionCard.tsx, components/actions/PhaseTimeline.tsx, fragments/action-card.fragment.ts, locales/en/actions.json, package.json, yarn.lock
Use themeable color consistently for completed && continuous actions
https://app.asana.com/0/1202855459841144/1207152962435939/f
=> Use actionContinuousColor

common/__generated__/graphql.ts, components/dashboard/ActionList.tsx, components/dashboard/ActionTableTooltips.tsx, components/dashboard/cells/IndicatorsCell.tsx, components/indicators/IndicatorList.tsx
Reduce n+1 queries due to changes in indicator visibility
Depends on this: https://github.com/kausaltech/kausal-watch-private/pull/191
=> Reducing unnecessary queries due to indicator visibility

components/common/TopToolBar.tsx, config/auth.ts, types/next-auth.d.ts, utils/session.utils.ts
Prevents the UI ending up in a logged in state but unable to actually retrieve restricted data.
=> Automatically logout when the session has expired

components/actions/ActionListFilters.tsx, package.json, yarn.lock
* Added the library to handle the escaping;
* Updated `filterAction` method;
Thread related to the bug  https://kausaltech.slack.com/archives/C01CZMVSM9C/p1721725603710529
=> Escape user input before using regex

components/Footer.tsx, components/MonsidoAccessibility.tsx
Integrate Monsido script and render it conditionally in the Footer based on the token (for Superior-sap).
Sibling PR https://github.com/kausaltech/kausal-themes/pull/32
Related Asana task https://app.asana.com/0/1205310117865974/1207663896451587/f
=> Integrate Monsido script

common/__generated__/graphql.ts, components/common/FeedbackForm.js, components/contentblocks/ExpandableFeedbackFormBlock.tsx, locales/en/actions.json
Feedback form to support category as feedbacktype
Depends on this: https://github.com/kausaltech/kausal-watch-private/pull/238
Asana: https://app.asana.com/0/1206017643443542/1207572329789663
=> Feedback to support category

components/MonsidoAccessibility.tsx
More details in Asana task https://app.asana.com/0/1202880927552397/1207663896451587/f
=> Add Heatmap functionality to the Monsido script

components/common/GlobalNav.tsx, components/indicators/IndicatorProgressBar.tsx, components/orgs/OrgContent.tsx, package.json, queries/get-organization.ts, yarn.lock
- Make org page background color themeable, fetch better quality logo
- Make indicator showcase link hideable by theme
- Handle very small latest measurement bar edge case
- Use themeable colors for second nav bar
=> Some edge case fixes and themeable features

components/common/TopToolBar.tsx, components/indicators/IndicatorListFiltered.tsx, locales/de-CH/common.json, locales/de/common.json
=> Fix some icon references

common/__generated__/graphql.ts, components/graphs/IndicatorGraph.tsx, components/indicators/IndicatorHero.tsx, components/indicators/IndicatorValueSummary.js, components/indicators/IndicatorVisualisation.js, locales/de/common.json, locales/en/common.json, locales/fi/common.json, queries/get-indicator.ts
BEFORE we assumed the desired trend and that the goal is never reached
NOW we set the desired trend in admin and tell if the goal has already been exceeded
Also the trendline is shown if so set in admin
=> Use new indicator visualisation options

app/[domain]/[lang]/[plan]/(with-layout-elements)/indicators/page.tsx, common/__generated__/graphql.ts, components/indicators/IndicatorList.tsx, components/indicators/IndicatorListFiltered.tsx, queries/get-indicator-list-page.ts
Hide indicator level in indicator list based on backend setting
Asana: https://app.asana.com/0/1206017643443542/1208598430238816
Depends on backend: https://github.com/kausaltech/kausal-watch-private/pull/284
=> Indicator level can be hidden in indicator list based on backend setting

common/__generated__/graphql.ts, components/common/StreamField.tsx, components/contentblocks/ActionListBlock.tsx, fragments/stream-field.fragment.ts
It's hacky way to support also hiding the header for a customer request
=> Support custom header or hiding it in ActionListBlock

components/actions/TaskList.js, components/common/StatusBadge.tsx, locales/en/actions.json
Reverts kausaltech/kausal-watch-ui#424
=> Revert "Highlight the late tasks in the Action Task List"

common/__generated__/graphql.ts, common/__generated__/paths/graphql.ts, components/paths/CategoryCard.tsx, fragments/category.fragment.ts
Add "main goal" attribute to the category and display it on category cards
Asana https://app.asana.com/0/1206017643443542/1208682503861856/f
=> Add and display main goal attribute

common/__generated__/graphql.ts, common/__generated__/paths/graphql.ts, common/__generated__/paths/possible_types.json, common/__generated__/possible_types.json, components/paths/contentblocks/CategoryListBlock.tsx, fragments/category.fragment.ts
Asana - https://app.asana.com/0/1205310117865974/1208848029333963/f
* Updated the query to include indicators data for rendering the IndicatorSparkline component in the CategoryCard.
* Replaced the generic Card component with the CategoryCard in the CategoryListBlock
=> Integrate CategoryCard into CategoryListBlock

playwright.config.ts
Enable parallel playwright e2e testing with 2 workers
=> Enable parallel testing

components/dashboard/ActionList.tsx, components/dashboard/ActionStatusTable.tsx
This take the new GraphQL field `hasContactPerson` in the backend's `ActionResponsiblePartyNode` into use.
Required backend PR:
https://github.com/kausaltech/kausal-watch-private/pull/65
=> Fetch less data for action dashboard

components/actions/ActionContent.tsx, components/actions/blocks/ActionLeadParagraphBlock.tsx, locales/en/actions.json, queries/get-action.ts
based on this techsupport request: https://kausaltech.slack.com/archives/C07S6DT2ZHT/p1738851827053859
=> render fieldLabel for leadParagraph in action contents

components/dashboard/ActionTableTooltips.tsx, queries/get-organization.ts
Add more stuff to query.
Also make code not break if query doesn't have enough stuff.
=> Fix organization term in tooltip

components/indicators/IndicatorProgressBar.tsx
Handle an edge case when emissions have increased from the base value. Normalize by default in this case.
There is still a glitch in animation when toggling normalisation on/off.
Before:
After:
=> Handle reverse progression on indicator showcase

components/indicators/IndicatorListFiltered.tsx
Includes linting fixes
Before
After
Asana: https://app.asana.com/1/1201243246741462/project/1202855459841144/task/1208965534574955?focus=true
=> Remove link color from indicator list values

components/custom/IntroModal.tsx
Longmont request - `Let’s have the default setting be the opposite, so the “don’t show again” is unclicked. I don’t know how frequently visitors visit the site, so I want it to pop-up unless they ask it not to.`
=> Update checkbox to be unchecked by default

common/__generated__/graphql.ts, common/__generated__/paths/graphql.ts, components/graphs/IndicatorGraph.tsx, components/indicators/IndicatorVisualisation.js
Use the  new 
```
ticksCount
ticksRounding
valueRounding
```
settings in indicator visualisation to improve y axis rendering
(less duplicate values, user control on rounding)
=> Use new indicator axis settings on indicator graph

e2e-tests/tests/basic.spec.ts
Fixes the E2E tests which broke because new "bike lane" indicators were created and we're running the tests against production. The long term solution is to create a dedicated test environment.
=> Fix E2E tests
