- components/actions/TaskList.js
Todo task order ends up wrong due to reverse() being in-place method. Switch the order of generating the arrays.
> Quickfix: Todo task order

- package.json
Currently Node.js is required to be version 14.x. I added 15.x.
> Add support for Node.js 15.x

- common/utils.js
- components/actions/ActionContent.js
- components/actions/ActionHighlightsList.js
- components/actions/ActionsTable.js
- components/common/StreamField.js
- components/layout.js
- pages/[...slug].js
- pages/_app.tsx
- pages/index.js
This should adapt image-fetching queries to use the new Wagtail images instead of instances of the old model, which are removed in [the respective backend PR](https://github.com/kausaltech/kausal-watch-private/pull/23). Hopefully I found everything. I'm not really sure where we should request which rendition (size).
> Change queries to fetch Wagtail images instead of removed legacy images

- components/indicators/IndicatorList.tsx
- components/indicators/IndicatorListFiltered.js
In the indicators table, only display `usableForIndicators` theme categories in the themes column.
> Filter out categories that aren't indicator themes

- components/indicators/IndicatorList.tsx
- components/indicators/IndicatorListFiltered.js
Display the name chosen by the user for themes in the indicator table.
> Display customer-specific theme column label

- common/__generated__/graphql.ts
- components/indicators/IndicatorList.tsx
- components/indicators/IndicatorListFiltered.js
If a theme hasn't been linked to an indicator it will be hidden from the theme filter dropdown. The filtering logic contains a few nested loops, which aren't ideal, but this functionality will eventually be moved to the backend.
> Filter out unused themes from indicator filters

- components/common/Icon.js
- components/indicators/IndicatorListFiltered.tsx
- stories/common/Icon.stories.js
The indicator link was previously hard to find and raised by at least Äänekoski. This change makes the chevron icon a button to control expansion and the indicator name a link (consistent with our other tables).
A nice improvement here would be to remember the hierarchy expansion state between pages so that the user could easily navigate back and forth between nested indicators. We could think about this along side the bigger indicators redesign.
https://github.com/kausaltech/kausal-watch-ui/assets/15343658/3b6c461f-8743-4069-9f31-432159d0999e
> Update indicator table to make indicators accessible by name

- common/blocks.types.ts
- components/common/RichText.tsx
- components/common/StreamField.tsx
- components/contentblocks/AccessibilityStatementComplianceStatusBlock.js
- components/contentblocks/AccessibilityStatementContactFormBlock.tsx
- components/contentblocks/AccessibilityStatementContactInformationBlock.tsx
- components/contentblocks/AccessibilityStatementPreparationInformationBlock.tsx
- components/contentblocks/ActionCategoryFilterCardsBlock.tsx
- components/contentblocks/ActionHighlightsBlock.tsx
- components/contentblocks/ActionListBlock.tsx
- components/contentblocks/ActionStatusGraphsBlock.tsx
- components/contentblocks/CardListBlock.js
- components/contentblocks/CartographyVisualisationBlock.tsx
- components/contentblocks/CategoryListBlock.tsx
- components/contentblocks/CategoryTreeBlock.tsx
- components/contentblocks/FrontPageHeroBlock.js
- components/contentblocks/IndicatorGroupBlock.js
- components/contentblocks/IndicatorHighlightsBlock.tsx
- components/contentblocks/IndicatorShowcaseBlock.js
- components/contentblocks/QuestionAnswerBlock.js
- components/contentblocks/RelatedIndicatorsBlock.js
- components/contentblocks/RelatedPlanListBlock.tsx
- components/home/HeroFullImage.js
Add an autogenerated id to all `StreamField` blocks. For now they just follow the block index e.g. `#block-1` represents the first block in a page, in future we could improve the editor experience by allowing editors to add their own id.
> feat: support block anchor links 

- common/environment.ts
- components/common/GlobalNav.js
- components/common/GlobalNav.tsx
- components/header.js
- Use sticky navigation if defined in the theme
- Switch sticky nav to be the primary nav bar on small screens
- Render a nav spacer to fix jumping content while transitioning to sticky
Probably easier to review by commit, the first includes prettier fixes.
> Support themeable sticky navigation

- components/insight/InsightFilter.js
Bootstrap typehead breaks the layout displaying a clear button with a double cross outside the field.
* added import for react typehead CSS;
* added styles to Typehead to remove the redundant second cross
> Fixed typehead layout on indicator insight page

- components/common/LanguageSelector.tsx
If enabled in theme settings, hide chosen locales from the language selector. Requested by Longmont and Kokkola while they finalise their translations.
https://github.com/kausaltech/kausal-themes/pull/3
> feat: hide chosen locales from language selector

- common/categories.ts
- common/links.tsx
- components/actions/ActionHero.tsx
- components/actions/ActionListFilters.tsx
- components/contentblocks/ActionCategoryFilterCardsBlock.tsx
- components/dashboard/ActionList.tsx
- components/indicators/IndicatorList.tsx
Fixes the [broken Longmont umbrella plan indicator filtering](https://longmont-indicators.watch-test.kausal.tech/indicators)
Previously the category type identifier for filtering was hardcoded, this change uses the identifier of the first usable indicator category.
> fix: support filtering indicators by custom categories

- components/actions/ActionHero.tsx
Truncate bread crumb categories longer than 90 characters, show the full category name in a tooltip.
> Truncate long category names in breadcrumbs

- common/__generated__/graphql.ts
- components/actions/ActionHero.tsx
- components/actions/CategoryTags.tsx
1. Fix duplicate categories in the breadcrumb
2. Fix missing top level category: category hierarchies will be displayed in the breadcrumb up to three levels deep
> Fix missing breadcrumb categories and remove duplicates

- common/__generated__/graphql.ts
- components/actions/ActionHero.tsx
- components/actions/CategoryTags.tsx
- components/common/BadgeTooltip.tsx
[Asana 🎫](https://app.asana.com/0/1205166465928475/1205490606196024/f)
Now that we support category names up to 200 characters in length:
- Limit category badges to two lines for a more approachable UI
- Add category identifiers to badges for easier glanceability/ cross referencing 
Open thoughts (any preferences here @terotik?):
- Should we also truncate long categories in breadcrumbs? → Leaning towards yes – breadcrumbs will be really cumbersome with multiple 150+ char crumbs
- Should we also truncate long categories in card titles? → Leaning towards no
> Truncate long category names in category badges

- components/common/RichText.tsx
- components/common/StreamField.tsx
* Individual embeds: added responsive styles to iframes according to the received CSS classes;
* RichText embeds: added styles for the received responsive object class.
> Added responsive styles to embeds

- components/categories/CategoryPageContent.tsx
Fall back to legacy category page rendering if no blocks have been defined
> Ignore empty category page main templates

- common/__generated__/graphql.ts
- components/contentblocks/CategoryPageHeaderBlock.tsx
- pages/[...slug].tsx
Requested by Surrey who use illustrations as category icons. Editors can specify an icon size of small, medium or large under category type page → "Level layouts" → "Icon size"
> Support custom category icon sizes

- components/graphs/IndicatorGraph.tsx
- package.json
- yarn.lock
Improve drawing indicator graphs if `graphs.areaGraphs=true` in theme (should be in backend)
Also implement `graphs.showTrendline=false` theme setting (should be in backend)
From this:
to this (do not fill if multiple traces)
http://klima-winterthur.localhost:3000/indicators/1687
And from this:
to this (no trend line, fill also goal as per customer request):
http://klima-winterthur.localhost:3000/indicators/2056
> Improve area graphs and use trend line visibility setting

- common/__generated__/graphql.ts
- components/dashboard/ActionList.tsx
- components/dashboard/ActionTableTooltips.js
https://github.com/kausaltech/kausal-watch-ui/assets/664877/4d79ab6e-6a11-42a7-b66a-a83d7d6cf4c8
> Display status in actiondashboard phase tooltip

- .eslintrc.json
- package.json
- pages/_app.tsx
- yarn.lock
Add eslint warning for unused variables to aid refactors and avoid some copy pasta bugs.
> Add support for typescript eslint rules and warn on unused variables

- .husky/pre-commit
- components/graphs/IndicatorGraph.tsx
- components/indicators/IndicatorContent.js
Also updated the Husky pre-commit config to do properly load Node when committing via the VSCode UI
> Prevent plotly from clipping markers on axes

- components/actions/CategoryTags.tsx
> Fix id contrast for reverse colour category badges

- components/contentblocks/ActionListBlock.tsx
- components/contentblocks/CategoryPageHeaderBlock.tsx
to
---
- https://app.asana.com/0/0/1205802844678617
> Reduce use of category color on category page

- components/actions/ActionHighlightsList.tsx
The header can be optionally disabled, and the
default count changed. These are used in embeds
through query parameters.
> Reinstate action highlights header & action count

- components/common/SiteFooter.tsx
- package.json
- yarn.lock
** requires theme update **
https://github.com/kausaltech/kausal-themes/pull/7
- Use new theme variables to enable different footer colors for secondary footer content (Statement, Funding logos, Other logos)
- Style more than 3 extra logos smaller
Side effects:
If second footer contains statement AND otherLogos they are not adjacent anymore:
Needs more work to handle this edge case, but should be ok for now
---
- https://app.asana.com/0/0/1205750873498146
> Accommodate multiple logos on custom bgcolor in footer

- components/actions/ActionPhase.js
- components/dashboard/ActionStatusTable.tsx
- components/dashboard/ActionTableTooltips.tsx
- components/dashboard/cells/ImplementationPhaseCell.tsx
When both phase and status are shown in the action list table, hide the status colour and labels from the phase column content.
- Add `ActionTableContext` to support passing props and custom config down to action table cells
- Update `ActionPhase` to hide status related information if `status` is undefined – this component might benefit from a refactor at some point
---
- https://app.asana.com/0/0/1205802844678626
> Hide redundant action status visualisation

- common/preprocess.ts
- components/dashboard/ActionStatusGraphs.tsx
- locales/da/common.json
- locales/de/common.json
- locales/en/common.json
- locales/es/common.json
- locales/fi/common.json
- locales/sv/common.json
Replaces "Unknown" UI text with "No phase set" and "No status set in the action dashboard donut charts"
---
- https://app.asana.com/0/0/1205897920277763
> Update unknown status labels

- components/indicators/IndicatorProgressBar.js
- package.json
- yarn.lock
Also fix misaligned label on very short goal bars
before:
afters:
---
- https://app.asana.com/0/0/1206010535152027
> Get indicator showcase bar colors from theme

- components/indicators/IndicatorList.tsx
- components/indicators/IndicatorListFiltered.tsx
- components/indicators/process-indicators.ts
- components/indicators/tests/IndicatorList.test.ts
- components/indicators/tests/mocks.ts
- jest.config.js
This has been pushed to staging, so please test this out [there](https://pirkkala-ilmasto.watch.staging.kausal.tech/indicators).
More of a bandaid than a rewrite, this essentially splits the hierarchical and flat indicators before sorting to ensure the tree structure isn't sorted incorrectly.
I started to refactor `processCommonIndicatorHierarchy` before realising the bug was within the sorting, but have committed the test case for that function in case we refactor in future. The large `mocks` file contains an input and expected output from that function.
> Fix sorting of combined hierarchical and flat indicators

- common/ThemedGlobalStyles.js
- components/actions/ActionHero.tsx
- components/common/Breadcrumbs.tsx
- components/common/RichText.tsx
Make sure floating (image)elements inside richtext do not mess the layout
Before
After
> Contain floating elements in richtext

- components/common/Switch.js
- components/indicators/IndicatorProgressBar.js
Handle edge case where goal value is not available:
---
- https://app.asana.com/0/0/1206202710087677
> Allow no goal value on (normalized) indicator showcase

- common/preprocess.ts
- components/dashboard/ActionStatusGraphs.tsx
- components/graphs/StatusDonut.js
- tests/preprocess.test.ts
0. Refactor the phase donut implementation.
1. Don't count "inactive" actions as "no phase set"
2. Try to display in a clearer way that the percentage in the status donut does take into account the actions without any status set (not counted towards 100%, a question mark is displayed for that sector.) So the 73% in the example means that of all actions with a status set, 73% are not late or otherwise. Still, of all the actions, 1/4 doesn't have a status set at all.
> Fix several problems with dashboard action status donuts

- common/__generated__/graphql.ts
- components/common/StreamField.tsx
Depends on backend PR https://github.com/kausaltech/kausal-watch-private/pull/115
The first embed has "Full width" selected, the second doesn't
> Support full width embed blocks

- common/__generated__/graphql.ts
- components/actions/TaskList.js
- components/actions/blocks/ActionScheduleBlock.tsx
- components/graphs/Timeline.tsx
- queries/get-action.ts
- queries/get-plan.ts
- utils/dates.utils.ts
Related backend PR: https://github.com/kausaltech/kausal-watch-private/pull/118
Allows users to customise the date format of:
- Action start and end dates (both globally under `actionListPage.actionDateFormat` and per action under `action.dateFormat`)
- Action task due dates (both globally under `actionListPage.taskDateFormat` and per action under `task.dateFormat`)
Users can choose to display the full date, month and year, or just the year.
---
- https://app.asana.com/0/0/1205726733412166
- https://app.asana.com/0/0/1206004551588327
> Add support for custom action date formats

- components/actions/ActionListFilters.tsx
Fixes a bug where visiting the actions page with an unknown filter value in the search params crashes the entire page. 
| --- | --- |
| <img width="1057" alt="image" src="https://github.com/kausaltech/kausal-watch-ui/assets/15343658/9a2942f1-9fda-4731-8e1e-82f6be6dbe8e"> | <img width="1058" alt="image" src="https://github.com/kausaltech/kausal-watch-ui/assets/15343658/b12caece-bdaf-41bf-b0bd-edce018faf36"> |
---
- https://app.asana.com/0/0/1206475155503892
> Fix actions page with invalid filters

- common/environment.ts
- next.config.js
- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
The reverted commit was to test using a runtime environment variable in the Sentry config with the new Next.js setup. It doesn't work and seems like we'll need to convert the Sentry DSN env variable to a build-time variable, reverting this until then.
Reverts kausaltech/kausal-watch-ui#276
> Revert "Migrate Sentry DSN to env variable"

- .github/workflows/ci-e2e.yaml
- e2e-tests/context.ts
* Removed checking for serious accessibility violations due to the high volume of color contrast errors, which do not allow us efficiently identify navigation-related issues during testing. Temporarily test only for critical accessibility issues.
* Set up the default list of plan identifiers for CI GitHub e2e tests. The list can be modified in GitHub Actions UI before running tests.
> Update e2e tests for GitHub ci

- app/[domain]/[lang]/[plan]/(with-layout-elements)/actions/[id]/page.tsx
- app/[domain]/[lang]/[plan]/embed/v1/[...slug]/page.tsx
The action ID is encoded by Next, which then led to the action not being found when querying GQL. Decode:
- Action IDs
- Embed slugs
> Fix actions with special characters in their ID

- components/common/SiteFooter.tsx
- package.json
- yarn.lock
Center partner logos (otherLogos) and render them smaller in footer if there are more than 4
And larger and right-aligned if there are less
---
- https://app.asana.com/0/0/1206383173050598
> Improve partner logo placement and sizing

- app/[domain]/[lang]/[plan]/(with-layout-elements)/actions/page.tsx
- app/[domain]/[lang]/[plan]/(with-layout-elements)/indicators/[id]/page.tsx
- components/actions/ActionCard.tsx
- components/indicators/IndicatorVisualisation.js
- sentry.client.config.ts
1. Only report `inidicator/[id]` errors to Sentry if there's an error in the GraphQL response. This prevents unnecessary error logs for indicator 404s – [Sentry Error](https://sentry.kausal.tech/organizations/kausal/issues/4538/)
2. Fix error when `planScenarios` is undefined –  [Sentry Error](https://sentry.kausal.tech/organizations/kausal/issues/4537/events/bc175d1127e4461d9f5b019685be5178/)
> Fix Sentry errors and update config

- app/[domain]/[lang]/[plan]/UpdateApolloContext.tsx
- app/[domain]/[lang]/[plan]/layout.tsx
- components/providers/ApolloWrapper.tsx
- middleware.ts
- utils/apollo-rsc-client.ts
- utils/apollo.utils.ts
- utils/middleware.utils.ts
The `x-cache-plan-domain` and `x-cache-plan-identifier` headers were missing from GQL queries post Next.js upgrade. 
- To support setting cache headers from the RSC Apollo client, headers are set in middleware, read upon Apollo client initialisation and set as initial context
- To support setting cache headers from the client-side Apollo client, Apollo context is updated while rendering the plan page
- `headersMiddleware` reads the domain and plan ID from Apollo context and sets the query headers
> Add missing cache headers

- package.json
Use Next.js default browser support rather than our quite restrictive config, no major changes to the final bundle size.
> Next.js supports modern browsers with zero configuration.
> 
> - Chrome 64+
> - Edge 79+
> - Firefox 67+
> - Opera 51+
> - Safari 12+
https://nextjs.org/docs/architecture/supported-browsers
> Use Next.js' default browser support

- components/plans/PlanSelector.tsx
Modified PlanSelector to exclude the current plan that's displayed in the dropdown title from the dropdown menu.
Related Asana task https://app.asana.com/0/1206017643443542/1206474860552270/f
Before:
After:
> Exclude current plan from dropdown selection

- components/common/LanguageSelector.tsx
Minor visual bug: LanguageSelector slightly breaks the layout on mobile. Set the margin.
Before:
After:
> Set margin for languageSelector on mobile

- components/indicators/IndicatorHighlightCard.tsx
- components/indicators/IndicatorValueSummary.js
Hide the unit completely if "no unit" for an indicator is chosen.
---
- https://app.asana.com/0/0/1206593636246602
> Fix 'no unit' indicator unit being displayed

- components/actions/ActionContent.tsx
Do not error if action content block does not provide `meta.hidden` or `meta.restricted`
> Handle missing contentblock metadata

- components/common/AttributesBlock.tsx
Fixes a production bug triggering an uncaught `Cannot read properties of undefined (reading 'meta')` error. 
Link to reproduce: https://ilmastovahti.tampere.fi/teema/kest%C3%A4v%C3%A4-kulutus/kest%C3%A4v%C3%A4-liiketoiminta-ja-tapahtumat
Link to initial error trace: https://sentry.kausal.tech/organizations/kausal/issues/4741/events/8daf98ce984345c6afe9143c1aa7d69a/
> Fix uncaught error accessing meta

- README.md
- common/environment.ts
- utils/apollo.utils.ts
Debugging queries from React Server Components is a pain, with this we can set `LOG_GRAPHQL_QUERIES=true` to log all outgoing queries server side.
Example log:
```
📡 14:38:29.493Z 📡 Sending query GetPlansByHostname with variables:
{
"hostname": "sunnydale.localhost"
}
query GetPlansByHostname($hostname: String) {
plansForHostname(hostname: $hostname) {
domain {
hostname
basePath
status
statusMessage
__typename
}
domains {
hostname
basePath
status
statusMessage
__typename
}
primaryLanguage
... on Plan {
id
identifier
otherLanguages
__typename
}
__typename
}
}
🎬 End of query GetPlansByHostname
```
> Support debugging server side queries

- app/[domain]/[lang]/[plan]/(with-layout-elements)/actions/page.tsx
- common/__generated__/graphql.ts
- fragments/action-list.fragment.ts
- queries/get-actions-list-page.ts
It seems the core issue is on the backend, but this provides an urgent fix for a hard deadline tomorrow (US customer demo & launch).
The backend seems to only include categories associated with actions for the current plan when querying the action list page with `onlyWithActions`, it should also consider categories that are assigned to actions in subplans. This quick fix ensures that the `onlyWithActions` boolean in the `ActionListFilter` fragment is `false` if the action list page includes subplan actions.
This also renames the variables passed around for clarity.
| --- | --- |
| ![Screenshot 2024-03-04 at 15 52 39](https://github.com/kausaltech/kausal-watch-ui/assets/15343658/c9fffd25-948e-46e3-b685-6d449d2b4ea4) | …
> Fix missing categories from multiplan action page filters

- components/actions/ActionCard.tsx
- components/actions/blocks/action-dependencies/ActionDependenciesBlock.tsx
- components/actions/blocks/action-dependencies/ActionDependenciesGroup.tsx
- components/common/Icon.tsx
- locales/en/actions.json
- stories/ActionCard.stories.tsx
- stories/ActionDependenciesBlock.stories.tsx
- stories/RestrictedBlockWrapper.stories.tsx
Note, the icon in the screenshot is specific to San Diego. This should be demoed to and test by San Diego on Monday, I'm a bit concerned about the usability of such heavy popup tooltips.
> Add mini version of action dependencies for action cards

- components/actions/ActionContent.tsx
I had to refactor this to a grid layout to support ordering containers differently on mobile and desktop. On mobile, the containers follow the same order as before in one column: Top → Aside → Bottom
I've pushed this to staging for testing, reviewers please click through a few actions in different plans :) https://san-diego-cap.watch.staging.kausal.tech/actions/MLU-3.1a
|--|--|
| ![san-diego-cap watch-test kausal tech_actions_RE-2 3-SA-1](https://github.com/kausaltech/kausal-watch-ui/assets/15343658/8a6f4cc5-7ba3-41b3-a1a6-8b2c75134e1a) | ![san-diego-cap localhost_3000_actions_RE-2 3-SA-1](https://github.com/kausaltech/kausal-watch-ui/assets/15343658/380f006f-ed0a-4400-8117-5f9225547858) |
---
- To see the specific tasks where the Asana app for GitHub is being used, see …
> Fix empty space between top and bottom action content in two column layouts

- common/__generated__/graphql.ts
- components/actions/ActionContent.tsx
- components/actions/blocks/ActionRelatedActionsBlock.tsx
- queries/get-action.ts
Add support to the frontend to show the customizable heading (fieldLabel) and tooltip (fieldHelptext) for ActionRelatedActionsBlock
Related backend: https://github.com/kausaltech/kausal-watch-private/pull/138/
> fieldLabel, fieldHelptext for ActionRelatedActionsBlock. 

- fragments/action-list.fragment.ts
There's an issue with the frontend querying on `DashboardColumnInterface` which means custom `columnLabel`s are ignored. For now, I've updated this query to query the column label on each block directly until we find the underlying issue.
Further discussion [in Slack](https://kausaltech.slack.com/archives/C01AZ2V3656/p1711356737098769)
> Fix missing custom action dashboard table column names

- components/actions/blocks/ActionRelatedActionsBlock.tsx
- components/actions/blocks/action-dependencies/ActionDependenciesBlock.tsx
Makes titles and spacing consistent with other blocks on the action page
> Improve action page block consistency

- .github/workflows/ci-e2e.yaml
Implement nightly scheduled run of e2e tests via GitHub Actions workflow (01:00 EEST)
> Add cron schedule for nightly e2e test

- common/preprocess.ts
- components/dashboard/ActionStatusGraphs.tsx
- components/graphs/StatusDonut.js
1. Revert back to counting undefined statuses in all numbers. (They are a "bad" state assuming that a plan wants to use statuses in the first place. This will incentivize adding status. If a plan doesn't want to use statuses, the donut can be hidden).
2. Also show the percentage of undefined statuses again.
(unrelated) fix the clipping of the hover text elements in the plotly graph when the mouse is near the bottom of the graph
> Revert some changes made within the last months to the action dashboard status donut

- e2e-tests/context.ts
Added check for accessibility violations with serious impact (color contrast). Previously we tested only for issues with the critical impact.
> Add color contrast accessibility check to e2e tests

- components/common/ErrorBoundary.tsx
- components/common/ErrorPage.tsx
- components/common/StreamField.tsx
- locales/da/common.json
- locales/de/common.json
- locales/en/common.json
- locales/es/common.json
- locales/fi/common.json
- locales/sv/common.json
This wraps all stream field blocks in an error boundary to ensure errors don't bubble up to the page error boundary. 
|  Before | After |
| -- | -- |
| ![image](https://github.com/kausaltech/kausal-watch-ui/assets/15343658/247aa565-e1a9-4b42-9c6d-36c9ce54da7b) | ![image](https://github.com/kausaltech/kausal-watch-ui/assets/15343658/9965327e-43c4-4961-9dfa-1db77d3f151e) |
---
- https://app.asana.com/0/0/1206977791925325
> Add stream field error boundary

- common/search.ts
- components/MatomoAnalytics.tsx
- components/common/NavbarSearch.js
- components/common/SearchView.js
This fires a search event in Matomo whenever a visitor uses the plan search functionality
https://developer.matomo.org/guides/tracking-javascript-guide#internal-search-tracking
---
- https://app.asana.com/0/0/1206034053800035
> Add analytics on site searches

- .github/workflows/ci-e2e.yaml
Update workflow file to handle manually triggered and scheduled e2e tests.
* Set dynamically constructed base URL for each plan using plan identifiers list from GH secret for scheduled tests
* Apply individual sets of env variables for each type of test
> set workflow for scheduled tests in GH Actions

- components/actions/ActionContent.tsx
- components/actions/PhaseTimeline.tsx
- components/dashboard/ActionTableTooltips.tsx
- components/dashboard/cells/ImplementationPhaseCell.tsx
- locales/de/actions.json
- locales/en/actions.json
- stories/PhaseTimeline.stories.tsx
- stories/Timeline.stories.tsx
- stories/mocks/actions.mocks.ts
Replace completed phase with "Continuous" in the UI if `action.scheduleContinuous===true`
> Replace completed state for continuous actions

- components/actions/ActionCard.tsx
- components/contentblocks/ActionListBlock.tsx
- components/dashboard/ActionList.tsx
- utils/actions.utils.ts
Fixes an issue where action dependencies aren't rendered in `ActionListBlock`s. We only query the action id on action dependencies and we then need to add the entire action object from the actions array by id – this part was missing from the `ActionListBlock`.
| -- | -- |
| <img width="831" alt="image" src="https://github.com/kausaltech/kausal-watch-ui/assets/15343658/e56dc353-720f-4134-a0ac-0e7293e648b0"> | <img width="830" alt="image" src="https://github.com/kausaltech/kausal-watch-ui/assets/15343658/33d7ee13-9600-41c7-8c07-12df55635702"> |
---
- https://app.asana.com/0/0/1206999596040643
> Fix action dependencies rendered by action list blocks

- components/actions/ContactPerson.js
- queries/get-plan.ts
Hollywood wants this. (See [Asana task](https://app.asana.com/0/1205530220248804/1202900955351281/f).) This is the UI part that uses a new `PlanFeatures` field. The corresponding backend part is here: https://github.com/kausaltech/kausal-watch-private/pull/172
The backend must obviously be deployed before the UI.
> Show organization ancestors in contact person details only conditionally

- components/common/GlobalNav.tsx
A bug occurs in a multiplan with language selection: when navigating from child plans (where a language other than the primary is selected) to the parent plan via the home link, the locale is dropped from the URL, causing users to revert to the primary language.
Appended the locale to the absolute URL path when navigating from relative links.
Related Asana task https://app.asana.com/0/1203773030383185/1206977267986284/f
> Append locale to URL when navigating from relative links

- components/actions/ContactPerson.js
- components/actions/PhaseTimeline.tsx
- components/dashboard/ActionStatusTable.tsx
Nothing exciting, just stuff I noticed during my BITV accessibility testing.
- `<p>` elements were used for things that are clearly not paragraphs; replaced by `<div>`
- Sometimes `<th>` elements were nested in `<th>` elements. I un-nested them.
- Some column headers didn't have `scope="col"` set.
I also noticed that in the table on the indicator list page, there are no row headers. But I was too lazy to fix that now.
> Make minor improvements regarding accessibility

- common/preprocess.ts
- components/contentblocks/ActionStatusGraphsBlock.tsx
Add completed continuous actions to phase summary graphs
Fix reversed phase color order in some phase status bars
> Add continuous actions to phase summary graphs

- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
This will configure Sentry to send 10% of transactions, to avoid overloading our Sentry instance
https://docs.sentry.io/platforms/javascript/performance/
> Reduce Sentry sample rate

- components/actions/ActionContent.tsx
- components/dashboard/cells/StatusCell.tsx
The action dashboard status column and the action details page should show just the plain action status in locations designed to show it.
Action.statusSummary should be reserved for places with no room to separate status/phase, like ActionCards, and also the action tables in indicator pages.
> Show action.status in places where that is explicitly desired

- components/actions/ActionCard.tsx
- components/dashboard/ActionList.tsx
[Asana task](https://app.asana.com/0/1206017643443542/1207112938358823/f)
Unfortunately this creates links to whatever the view URL of an action is, so in a development deployment it will not point to localhost. But this seemed to be the case already before for cross-plan action links in general.
> Fix links to cross-plan merged actions

- app/[domain]/[lang]/layout.tsx
Some `globalThis is not defined` errors are still popping up in old browsers, there's a possibility that the polyfill is loaded after `globalThis` is used
[Sentry error](https://sentry.kausal.tech/organizations/kausal/issues/723/?alert_rule_id=4&alert_type=issue&environment=production&notification_uuid=45e01212-d11e-4656-9a56-4a3e4b1e4288&project=2&referrer=slack)
> Ensure global this polyfill is added before hydration

- components/actions/ActionLogBanner.tsx
Raúl reported that the action pages are throwing errors when signed in to the public UI. @tituomin is it valid that `matchingVersion` can be `null` or should that be fixed on the backend?
https://sentry.kausal.tech/organizations/kausal/issues/804/
> Prevent uncaught error if matchingVersion is null

- common/__generated__/graphql.ts
- components/actions/ContactPerson.js
- components/actions/ContactPerson.tsx
- queries/get-plan.ts
Hide avatars if plan feature setting requires it.
To signal "leader" we show a left border instead of the circle around the avatar.
Depends on:
Backend: https://github.com/kausaltech/kausal-watch-private/pull/206
Asana: https://app.asana.com/0/1206017643443542/1207437856881925
> Hide avatar based on plan feature setting

- components/actions/ActionCard.tsx
- components/actions/ActionHero.tsx
- components/actions/ActionUpdatesList.js
- components/actions/ContactPerson.tsx
- components/dashboard/cells/OrganizationCell.tsx
- components/plans/PlanChip.tsx
- components/plans/PlanSelector.tsx
* Replaced hardcoded paths for default avatar images with theme variables;
* Applied `getThemeStaticURL()` to dynamically fetch the image URLs
Description in Slack https://kausaltech.slack.com/archives/C01AZ2V3656/p1722333114206229
> Replace avatar image paths with theme variables

- components/actions/ContactPerson.tsx
Display an empty circle when the avatar image is not provided (and not intentionally hidden).
* Replaced the `img` element with a styled `div` to get more control over avatar's placeholder;
* Added `hasAvatar` prop for conditional rendering;
* Removed the default path;
* Added `aria-label` for accessibility.
Before:
After:
> Refactor: Handle absent avatars

- components/graphs/IndicatorGraph.tsx
- components/indicators/IndicatorValueSummary.js
When we are less than a year from the indicator goal, the summary displays 0 years
Use `dayjs().to` to make time-to-goal human readable and localised
Add "+" to emphasise expected increase as opposed to decrease
Also added a few quick customer requested improvements on plotly graph formatting.
> Format time-to-goal better

- components/GoogleAnalytics.tsx
- components/Header.tsx
Integrate Google Analytics script (a customer request):
* Added a new GoogleAnalytics component with a `trackingId` prop;
* The component conditionally loads the GA script based on the `googleAnalyticsId` theme variable.
Related Asana https://app.asana.com/0/1202880927552397/1207663896451596/f
> Implement Google analytics script

- app/[domain]/[lang]/[plan]/(with-layout-elements)/[...slug]/ContentPage.tsx
- components/actions/ActionHero.tsx
- components/common/Accordion.tsx
- components/common/RichText.tsx
- components/contentblocks/CategoryPageHeaderBlock.tsx
- components/contentblocks/ContentPageHeaderBlock.js
- components/home/HeroFullImage.tsx
- components/home/HeroSmallImage.tsx
- components/indicators/IndicatorProgressBar.tsx
- package.json
- yarn.lock
- make image credit smaller and always in top right corner of the header image
- Reverse Q&A coloring
- Force wrapping of overflowing words in richtext columns
- Hide goal related content when it's not available for normalised values in indicator showcase
- Up themes
before:
after:
before:
after:
> Various bug and style fixes

- components/GoogleAnalytics.tsx
Fix the missing tracking data issue with Google Analytics script.
* Added the missing external script;
* Used NextJS `strategy="afterInteractive"` to load scripts.
> Add external script

- components/common/NavbarSearch.js
The bug was caused by the previous fix: applying `React.memo` for `NavbarSearch` component to prevent unnecessary re-renders. 
When a user enters a keyword in the navbar search, clicks on the "See all results" link and gets redirected to the Search page, the result box is still displayed, but after closing it "No results for this search..." message is displayed, even though there were search results.
https://github.com/user-attachments/assets/ddfa0d58-cc39-4101-83ed-ff2692ceb0fc
* Added `closeSearch()` in the ResultList to close the result box after the link is clicked, redirecting the user to the search page;
* Removed `setSearchTerm('')` to ensure that the search term is passed and the results are displayed on the Search page.
After: …
> Close result box after navigation to search page

- components/graphs/IndicatorGraph.tsx
- components/indicators/IndicatorVisualisation.js
RE: [Asana](https://app.asana.com/0/0/1208165767809303/f)
Make sure that all traces follow same (YEARLY/MONTHLY) date format when passed to graph
Calculate a proper xtick interval for date axis instead of trusting Plotlys auto feature that gives us double years for example:
**BEFORE**
**AFTER**
Also remove unused properties from plotly data/layout objects to silence console warnings
> Formatting plotly x axis years (again)

- common/__generated__/graphql.ts
- components/dashboard/ActionList.tsx
- components/dashboard/dashboard.constants.tsx
Show short identifier/abbreviation instead of plan avatar in action dashboard when short_identifier is defined in admin Plan settings.
Depending on backend: https://github.com/kausaltech/kausal-watch-private/pull/266
Asana: https://app.asana.com/0/1206017643443542/1208235388125365
> Short identifier for plan shown in action dashboard if defined

- components/actions/ActionListFilters.tsx
Introduced in 06e9a542452e8190ef390f6c06b88eb6683d76b8 - after having
escaped the user provided search string for use as a regular
expression, the identifier search broke since it was not implemented
as a regular expression search but simple string matching. For example
dashes in identifiers like AB-CD-1 where not matched because they are
a special character in regex and had been escaped.
> Fix bug in Action List Page text search regex handling

- components/indicators/IndicatorVisualisation.js
The trendline label was missing and was showing as "trace 1" instead of "trend"
Before:
After:
> add label for trendline

- components/indicators/IndicatorVisualisation.js
A bug: The trend line was not extending to the correct goal year in the Indicator graphs.
Asana https://app.asana.com/0/1206017643443542/1208538004462773/f
We were getting `highestGoalYear: NaN`. 
Modified `highestGoalYear` to extract and parse the last element of the `x` array.
Before:
After:
> Fix trend line not extending to the goal year

- app/[domain]/[lang]/[plan]/(with-layout-elements)/indicators/page.tsx
- common/__generated__/graphql.ts
- components/actions/ActionListFilters.tsx
- components/indicators/IndicatorList.tsx
- components/indicators/IndicatorListFiltered.tsx
- queries/get-indicator-list-page.ts
Use relatedPlanIndicators in umbrella plan instead of planindicators. Filter by relatedPlanIndicators common categories instead of planIndicator categories
> Use relatedPlanIndicators in umbrella plan. Filter by common categories.

- components/actions/TaskList.js
- components/common/StatusBadge.tsx
- locales/en/actions.json
UI improvement: Display late tasks as late in action task list - Asana https://app.asana.com/0/1205310117865974/1207617873637474/f
* Reused `StatusBadge` component for visual consistency to mark the late tasks within the `ListGroupItem`.
* Highlighted the entire `ListGroupItem` when a task is marked as late, using the background color from the StatusBadge/late.
* Added English translations for the "Late" label.
To do next: Add translations for the "Late" label via Weblate to support other languages.
> Highlight the late tasks in the Action Task List

- components/common/BadgeTooltip.tsx
A visual bug fix: Category badges text gets vertically clipped (for letters like "g" or "j").
Asana - https://app.asana.com/0/1206017643443542/1206601794961315/f
* Updated styles for `StyledBadge` to align the badge text vertically.
Before:
After:
> Add styles to avoid text clipping

- components/dashboard/ActionStatusExport.js
- locales/en/common.json
The new column is only added when there are multiple plans in the dashboard, which can happen for umbrella plans.
https://app.asana.com/0/1205307984231852/1208281478512987/f
> Add plan name column to action dashboard export

- components/indicators/IndicatorHighlightCard.tsx
Fix: Inconsistent indicator value decimal point in the Indicator highlight card - Asana https://app.asana.com/0/1206017643443542/1208816853419121/f
* Added `useLocale` hook and updated the `beautifyValue` function to use locale for number formatting consistency
> Apply locale for consistent number formatting

- components/dashboard/dashboard.constants.tsx
- fragments/action-list.fragment.ts
This has to be merged and deployed first, only then can the backend without the ImpactColumnBlock be deployed.
> Remove ImpactColumnBlock

- components/common/GlobalNav.tsx
Fix an issue when clicking on the LogoLink directed users to an URL with doubled locale on the first click.
Asana - https://app.asana.com/0/1206017643443542/1208913102229360/f
* Modified `getRootLink` logic to check if `locale` is already included in `viewUrl`.
> Fix URL construction for LogoLink

- components/contentblocks/IndicatorGroupBlock.tsx
Bug: `SectionHeader` text color in the `IndicatorGroupBlock` is not readable in some cases, due to the `readableColor` logic, which caused the text color to be overridden if color contrast insufficient.
The bug appears after applying SectionHeader to the Indicators block for visual consistency with the ActionListBlock. 
* Removed `readableColor` logic from h2.
Asana https://app.asana.com/0/1206017643443542/1208963765257879/f
> Resolve SectionHeader contrast issue in IndicatorGroupBlock

- components/common/GlobalNav.tsx
followup to: https://github.com/kausaltech/kausal-watch-ui/pull/441/files
the first fix did not work because the viewurl included `/<locale>` and not `/<locale>/ `
> Another fix URL construction for LogoLink

- components/actions/ActionListFilters.tsx
Handle situations where action list filters background color is the same as primary button color:
By using secondary button in those cases
> Handle button color exception on actionlist filters

- next.config.js
See https://www.npmjs.com/package/@sentry/webpack-plugin#errorhandler for documentation.
> Do not block builds completing because of Sentry unavailable

- components/indicators/IndicatorVisualisation.js
Use showTotalLine setting on indicator graphs
BEFORE:
AFTER:
> WIP: Hide total line on indicator graphs as per setting

- common/i18n.ts
- components/actions/ActionListFilters.tsx
- components/indicators/IndicatorList.tsx
- locales/de/common.json
- locales/en/common.json
Adjust text for filter label on Indicator dashboard - Asana https://app.asana.com/0/1206017643443542/1208871410132335/f
* Added optional `actionTerm` parameter to `getActionTermContext`;
* Updated `IndicatorList` to pass `actionTerm: 'INDICATOR'` for the correct context;
* Added `INDICATOR` context to the `filter-text` in locale files (EN and DE).
Before:
After:
To do next: Add the rest of translations for `filter-text` via Weblate.
> Adjust filter label text on indicators page

- components/dashboard/cells/DateCell.tsx
- components/dashboard/dashboard.constants.tsx
In `ActionStatusTable` Start and End Date columns have inconsistent styling to other columns - Asana https://app.asana.com/0/1206017643443542/1209097282477368/f
* Added a reusable `DateCell` component for consistent styling and date formatting for the date columns;
* Applied the `DateCell` to the related column blocks in the `COLUMN_CONFIG`.
Before:
After:
> Make date columns styling consistent

- components/actions/ActionCard.tsx
[](url)Align vertically `SecondaryIconsContainer` at the bottom of ActionCard 
Asana https://app.asana.com/0/1205310117865974/1209137870225632/f
* Updated styles for `ActionCardElement` and `SecondaryIconsContainer` to use flexbox.
Before:
After:
> Align SecondaryIconsContainer vertically

- .github/workflows/ci-e2e.yaml
Fix failing e2e tests in GH Actions.
GitHub actions recently switched Ubuntu version from 22.04 to 24.04.
The Playwright installation step in the GitHub Actions failed because of missing dependencies when using `ubuntu-latest`.  Set the runner to the previous version - Ubuntu 22.04.
> Set GitHub Actions runner to ubuntu-22.04

- components/actions/ActionListFilters.tsx
Search text badge is disappeared from the ActionListView filter section - Asana https://app.asana.com/0/1206017643443542/1209138285063386/f
Regression bug: the logic of handling boolean filters could cause `name` filters string values return null.
* Refactored `createBadge` function:
Improved validation for `name` filter, logic for `boolean` and `options` filters
Before:
After:
> Display search text badge again

- components/graphs/IndicatorGraph.tsx
- package.json
- yarn.lock
Dependency: https://github.com/kausaltech/kausal-themes/pull/39
Before merging Patchenstein, moving some customer specific settings from there to `master`
Only visible change in existing graphs should be `hoverformat`:
BEFORE
AFTER
**Via settings we can now set:**
- Fill for trace markers
- Symbol types for all trace markers
- Colors of all traces
- If goals are connected with line
**User need:** 
- Filled circle markers
- Specific color for main trace and goal trace
- Line connecting goal points
> Use graph visual settings from theme

- common/links.tsx
- components/dashboard/dashboard.constants.tsx
Multiplan organization page action links are not linked to the correct plans - Asana https://app.asana.com/0/1206017643443542/1209193372014336/f
* Updated `ActionLink` to prepend `planUrl`;
* Added `planViewUrl` as a fallback for cross-plan links.
There is a difference in domain structure between local/testing and production environments for Ludwigsburg (e.g `ludwigsburg-stadtteile` in test and `ziele.ludwigsburg.de/stadtteile` in prod), so I can't test this fix properly.
> Make action links in multiplan redirect to the correct plan

- components/actions/ActionCard.tsx
- components/actions/ActionHero.tsx
- components/actions/ActionHighlightCard.tsx
Change `hyphens` from `manual` to `auto` for all languages except Finnish - Asana https://app.asana.com/0/1206017643443542/1208784984047146/f
We get `hyphens: manual` from backend for `action.name` and need to use that for Finnish language. For other languages should be applied `hyphens: auto`.
* Applied the css `lang(fi)` pseudo-class to the specific components to achieve that.
> Apply based on language hyphenation for action.name

- components/actions/ActionContent.tsx
- components/actions/CategoryTags.tsx
- components/indicators/IndicatorContent.tsx
A bug: Category tags are double-counted on Indicator Details Page - Asana https://app.asana.com/0/1206017643443542/1209302839473157
The problem is caused by the types array containing duplicated types
* Removed the unnecessary `types` prop from `CategoryTags`;
* Used `Map` to avoid duplication of category types;
Before:
After:
> Remove duplicated types in CategoryTags

- .github/workflows/ci-e2e.yaml
Update deprecated since 31.01.2025 GitHub Actions v3 to the latest v4 in the E2E tests workflow.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Update deprecated GitHub Actions to v4

- common/images.js
- components/actions/ActionCard.tsx
- components/common/SearchView.js
- components/contentblocks/CardListBlock.js
- components/contentblocks/RelatedPlanListBlock.tsx
- components/indicators/IndicatorContent.tsx
- components/orgs/OrgContent.tsx
An image does not necessarily have a rendition, as per the GraphQL schema, for whatever reason. Our code did not take this into account and would crash if an image has no rendition. This seems to have been the cause for the following errors:
- https://sentry.kausal.tech/organizations/kausal/issues/4039/
- https://sentry.kausal.tech/organizations/kausal/issues/4033/
Corresponding Asana task:
https://app.asana.com/0/1206017643443542/1209261486348088
> Avoid crashing if an image does not have a rendition

- components/actions/CategoryTags.tsx
Truncate category badge differently based on text length to avoid short text truncation
To avoid truncation like this: 
while still keeping truncation like this:
For context: tech support request: https://kausaltech.slack.com/archives/C031Z5WMGJ0/p1739343482188709?thread_ts=1739285052.927909&cid=C031Z5WMGJ0
> Truncate category badge differently based on text length

- components/common/Icon.tsx
Regression bug: The SimpleLanguage and SignLanguage icons were missing from the Bremen navbar because they were not included in the AvailableIcons enum - Asana https://app.asana.com/0/1206017643443542/1209444524338843
> Add missing icons to AvailableIcons

- components/common/BadgeTooltip.tsx
Fix width clipping some badges
Also fix descending letters clipping
From this:
To this (localhost so no icons showing) :
> fix icon badges from clipping text and descending letters

- components/versioning/PlanVersionSelector.tsx
Improvement: Highlight the currently active plan version in the PlanSelector dropdown.
Asana - https://app.asana.com/0/1206017643443542/1209507933492392
> Highlight active plan version

- components/actions/ActionHighlightCard.tsx
Align action identifier display in `ActionHighlightCard` with `ActionCard` (on top left corner of the card). 
Initially it was requested by a customer (Asana https://app.asana.com/0/1206017643443542/1209168011618229), but we decided to apply the adjustment across all plans.
Before:
After:
> Display identifier consistently across action cards

- components/dashboard/ActionStatusExport.js
Implements a [feature request](https://app.asana.com/1/1201243246741462/project/1206017643443542/task/1209631179643361?focus=true) to filter the actions included in Excel exports.
It requires a [corresponding backend PR](https://github.com/kausaltech/kausal-watch-private/pull/351) to be effective, but deploying this before the backend PR is merged should be fine.
> Filter actions included in Excel exports

- components/indicators/IndicatorContent.tsx
A bug: Category tags are double-counted on Indicator Details Page - https://lappeenranta.test.kausal.tech/lumo/indicators/3894
Asana https://app.asana.com/0/1206017643443542/1209302839473157
The problem is caused by the types array containing duplicate types.
* Added `uniqueTypes` to remove duplicates so only unique types (based on their id) are passed to the CategoryTags.
> Fix duplicated category tags on indicator page

- app/[domain]/[lang]/[plan]/(with-layout-elements)/[...slug]/page.tsx
- app/[domain]/[lang]/[plan]/(with-layout-elements)/page.tsx
- app/[domain]/[lang]/[plan]/layout.tsx
- utils/apollo.utils.ts
- utils/middleware.utils.ts
The way nextjs routing works is that it checks if a static file exists in the filesystem and if it does not, it will move on to routing through the application. This results in missing static files causing errors in app code.
Fix this problem by marking the static file requests specially in the middleware and exiting early from app code if the request is thus marked. We need to modify both the app layout and the middleware, because inside the middleware we do not yet know if the static request will be succesful. Only unsuccesful requests end up in the app code.
> Fix problem with _next/static.* file requests ending up in app code

- app/global-error.tsx
- components/common/ErrorPage.tsx
We can't use translations in the root global error as the translations provider exists in the layout component and `global-error` is designed to wrap and catch layout errors. NextIntl's `useMessages` also doesn't work in `global-error.tsx`. This caused an uncaught error to be thrown in `global-error.tsx` (how meta), as the `ErrorPage` component uses `useTranslations.`.
Avoid rendering `ErrorPage` and just render the necessary content directly in `global-error.tsx`. Note that all global errors will now be in English, however 99.99% of errors will be caught further down the tree by `error.tsx` boundaries.
> Fix root global error

- components/actions/ActionCard.tsx
- components/common/BadgeTooltip.tsx
- components/contentblocks/CategoryPageHeaderBlock.tsx
If category icon is svg always render it smaller and apply catogory color or brandDark
Before actionCard
After actionCard
Before categoryBadge
After categoryBadge (also fixed some padding)
before categoryPage
after categoryPage
SVG should be formatted as typical svg icon (so no outlines, just fills)
If the admin wants to use colourful icons, png format should be used. Png does render also larger in badges to accomodate SDG categories.
> Handle svg category icons consistently

- common/dayjs.ts
- components/graphs/GraphAsTable.js
Indicator years in data table in public UI do not match the years in admin UI  - Asana https://app.asana.com/1/1201243246741462/project/1206017643443542/task/1210078915968237?focus=true
The browser interpreted dates like midnight in Finnish time as the previous day in UTC, which made the displayed year shift back. 
* Added `utc` plugin to `dayjs` setup.
* Used the raw date `rowObj.raw` instead of formatted label for trace lookups.
> Fix years mismatch due to timezone difference

- components/actions/CategoryTags.tsx
Fix for: https://app.asana.com/1/1201243246741462/project/1206017643443542/task/1210204441071810
> Try to show category level name only if category level is defined

- components/indicators/IndicatorProgressBar.tsx
Indicator showcase bugs if the indicator goal is 0
Not anymore!
> Handle zero goal on indicator showcase

- components/actions/ActionImpact.js
- components/actions/ResponsibleList.tsx
- components/common/BadgeTooltip.tsx
Refreshed this old PR as an use case came up. Ability to color the badges differently from themes. 
Theme change has already been applied and released.
Before: `brandDark` only
After: with `badgeColor`
'Badge' is probably not the modern term for these elements, but let's keep it like that for legacy's sake.
> Use custom badge color

- common/__generated__/graphql.ts
- components/common/Card.tsx
- components/contentblocks/DashboardRowBlock.tsx
- components/contentblocks/indicator-chart/DashboardIndicatorPieChartBlock.tsx
- components/contentblocks/indicator-chart/indicator-chart-colors.tsx
- fragments/dashboard-indicator-block.fragment.ts
Add the indicator pie chart component and update the dashboard row styles. Parts of this chart will may be useful for the other visualisations. Let's separate those to helper functions/ constants as needed.
| Input | Output |
|--|--|
| ![image](https://github.com/user-attachments/assets/514c359b-36a3-44e3-ab31-1a65838897eb) |  <img width="547" alt="image" src="https://github.com/user-attachments/assets/814a876e-a53d-4d90-85c1-cead33410b81" /> |
| ![image](https://github.com/user-attachments/assets/3456b8dd-fffb-43ce-a882-ce6bf89f3504) | ![image](https://github.com/user-attachments/assets/f9f04c3b-41ca-406d-8ae4-0164ac013c87)) |
| Input | Output |
|--|--|
|  ![image](https://github.com/user-attachments/assets/42d9ade0-5525-40e1-8ad1-73c5a97424d1) | …
> Add indicator pie chart

- components/common/BadgeTooltip.tsx
Button makes these center aligned - only visible when multiple lines
Let's make them all align left
Also adjust line-height making sure clipping & clamping work
-->
https://app.asana.com/1/1201243246741462/project/1206017643443542/task/1210397264254534?focus=true
> Align badge text always left

- components/common/StreamField.tsx
Bug fix - Embeds were displayed at the wrong height.
Asana https://app.asana.com/1/1201243246741462/project/1206017643443542/task/1210470076974007?focus=true
Remove the global height: 100% style for iframes to fix overriding issues with embeds
> Fix: remove global height overriding iframe height

- components/common/StreamField.tsx
Fix for an issue where ArcGIS embeds ignore the selected in the admin embed size (small, medium, large) and always rendering at a large height.
Asana - https://app.asana.com/1/1201243246741462/project/1206017643443542/task/1210518770420421?focus=true
* The iframe content from ArcGIS sets its own height that overrides our responsive styling.
* Added a style block for ArcGIS embeds with fixed heights for the selected sizes and applied `!important` to override ArcGIS's default.
> Apply selected in admin size to ArcGIS embeds

- components/contentblocks/DashboardRowBlock.tsx
- components/contentblocks/indicator-chart/DashboardIndicatorAreaChartBlock.tsx
- components/contentblocks/indicator-chart/DashboardIndicatorBarChartBlock.tsx
- components/contentblocks/indicator-chart/DashboardIndicatorLineChartBlock.tsx
- components/contentblocks/indicator-chart/indicator-charts-utility.ts
- fragments/dashboard-indicator-block.fragment.ts
Add the new blocks for the bar and area charts based on e-charts for indicators visualisation. 
Asana tasks: https://app.asana.com/1/1201243246741462/project/1206017643443542/task/1210259161444271?focus=true and https://app.asana.com/1/1201243246741462/project/1206017643443542/task/1210259161444275?focus=true.
* Implemented Bar Chart Block:
- Dynamically renders grouped or stacked bars based on the admin settings;
- Supports both total and dimensions with categories.
- Bar charts don't support trendlines or goal markers.
* Implemented Area Chart Block:
- Supports both total and dimensional indicators.
- Displays total and trendline only when no dimension is selected (for total values only).
- Don't support goal markers.
* Added support for the admin indicator visualisation settings: …
> Bar and area charts for indicator visualisation 

- components/contentblocks/indicator-chart/DashboardIndicatorAreaChartBlock.tsx
- components/contentblocks/indicator-chart/DashboardIndicatorBarChartBlock.tsx
- components/contentblocks/indicator-chart/DashboardIndicatorLineChartBlock.tsx
- components/contentblocks/indicator-chart/indicator-charts-utility.ts
Unit label on Y-axis cropped if it's long  - Asana https://app.asana.com/1/1201243246741462/project/1209894862159781/task/1210615499515662?focus=true
* Applied padding to the y-axis label to prevent cropping
Before:
After:
> Make gridLeft dynamic based on unit name length

- components/contentblocks/indicator-chart/DashboardIndicatorAreaChartBlock.tsx
- fragments/dashboard-indicator-block.fragment.ts
Support admin-controlled stacking in area charts
Asana - https://app.asana.com/1/1201243246741462/project/1209894862159781/task/1210617059962014?focus=true
* Added `dataCategoriesAreStackable` field to the GraphQL query;
* Enable admin-controlled stacking in the area chart.
> Support stacking option for area charts

- locales/da/common.json
- locales/de/common.json
- locales/el/common.json
- locales/en/common.json
- locales/es/common.json
- locales/fi/common.json
- locales/lv/common.json
- locales/pt-BR/common.json
- locales/sv/common.json
Add "data-not-available" locale string used in indicator graphs for all languages.
> Add missing translations for the data-not-available string

- src/components/contentblocks/indicator-chart/DashboardIndicatorAreaChartBlock.tsx
Indicators Dashboard: Visually align area chart legends with pie (or bar) charts.
Asana - https://app.asana.com/1/1201243246741462/project/1209894862159781/task/1210912656811919?focus=true
* Override area charts legends to use `roundRect` icons (like pie-charts).
Before:
After:
> Override legends for area charts to match pie

- e2e-tests/__generated__/graphql.ts
- src/common/__generated__/graphql.ts
- src/common/__generated__/possible_types.json
- src/components/actions/ActionCardList.tsx
- src/components/common/StreamField.tsx
- src/components/contentblocks/ActionListBlock.tsx
- src/fragments/stream-field.fragment.ts
Add category-level grouping to `ActionListBlock` on `Category` pages.
Plymouth request: Actions should be grouped by the selected in Admin `CategoryLevel` (child or grandchild of the page category) and rendered as list sections with two headings: intermediate parent + selected level. Now all actions are displayed as a flat list even when they have that setting in Admin.
Implement grouping modes: `oneLevel` (child) and `twoLevels` (grandchild under page).
Kept inner grouping by `org` (primaryOrg → none fallback).
Asana: https://app.asana.com/1/1201243246741462/project/1206017643443542/task/1211392323171602?focus=true
Depends on `Group by level` setting in Admin for the relevant Category page
Test case Priority-Plymouth that has 2 levels of headings for Category page - …
> CategoryPage: Group actions by category levels
